### ISSUE TITLE
update protocol, save in a separate file

### ISSUE THREAD

**Issue by xqu** [xqu/biofeedback#1]
update the protocol so that we always store the Muse data in a separate file

**Comment by VenusMeow** [comment]
Read muse's developer documentation and try to save the file to muse file and also osc file.

**Comment by xqu** [comment]
http://developer.choosemuse.com/

**Comment by VenusMeow** [comment]
Here's something they already have for saving to and converting between the native Muse file format (.muse), Matlab (HDF5), CSV, and .txt (OSC replay) formats.
http://developer.choosemuse.com/research-tools/museplayer

**Comment by xqu** [comment]
明天开会之前，看懂现有程序，怎么连上muse band，那个文件，那几个function。 然后，寻找类似例子，如何调用Museplayer，在JavaScript里面，然后文件另存为什么格式。

**Comment by xqu** [comment]
在JavaScript里面，然后文件另存为什么格式。调用什么现有程序，比如muse player

**Comment by xqu** [comment]
http://developer.choosemuse.com/research-tools/available-data

**Comment by xqu** [comment]
https://kb.brandeis.edu/display/LTS/MATLAB

**Comment by xqu** [comment]
http://developer.choosemuse.com/research-tools/museplayer/command-line-options

**Comment by VenusMeow** [comment]
muse-player的存文件问题：成功的example
1. 先建一个空的desired file e.g. Desktop/recording.txt
(sidenote: 未来javascript需要code建空文档）
2. 不要连muselab等其他软件占用port
3. 之后指令：e.g. muse-player -l 5000 -O Desktop/recording.txt 就可以用了

**Comment by werdnaH** [comment]
新建文件recording.txt 于桌面之后，一下代码为向文件写入 5000端口的input
PS C:\Users\Andrew> muse-player -l 5000 -O Desktop/recording.txt
Muse Player 1.8.4
Input:
5000
  * OSC port: tcp:5000 (Hit Control-C to stop)

Output:
  * OSC-replay file: Desktop/recording.txt
Playback Time: 0.2s : Sending Data

**Comment by werdnaH** [comment]
Muse lab 安装后运行显示 can't find the name of Intel ICD OpenGL driver

**Comment by werdnaH** [comment]
运行 muse-lab.jar 可以解决

**Comment by xqu** [comment]
我们现在新的需求是这样。我们的用户场景是不需要看线的，主需要存文件。处理文件，给出声音反馈，不需要图像反馈。原因是，我们假设用户看书和pdf的时候，眼睛关注在书和pdf上，线是distracting，所以，我们一切反馈都是从声音走。从最简单的audio notification开始，将来可能类似amazon alaxa，直接人机对话。

**Comment by xqu** [comment]
we continue the discussion in issue #9

**Comment by xqu** [comment]
good question: web app or mobile, we expect to do both, whichever is a low-hanging fruit, we start first, basically, use existing solution as much as possible.

**Comment by xqu** [comment]
R spend time on Android, and Venus investigate iPhone.

**Comment by xqu** [comment]
merge to #13
