### ISSUE TITLE
Who is windows 10 users?

### ISSUE THREAD

**Issue by xqu** [xqu/biofeedback#12]
http://developer.choosemuse.com/research-tools/getting-started

**Comment by xqu** [comment]
https://play.google.com/store/apps/details?id=com.interaxon.muse&hl=en

**Comment by xqu** [comment]
R is using Android, while Sean and Venus are using iphone.

**Comment by VenusMeow** [comment]
http://forum.choosemuse.com/t/collect-brainwave-data-easily-and-prototype-faster-with-muse-direct/2104

**Comment by xqu** [comment]
Key Features
• Easy-to-use GUI
• Connect to multiple headbands via Bluetooth
• Stream live data to one or many computers simultaneously
• One-click recording
• Receive and stream raw data from the Muse headband including EEG, accelerometer, gyroscope, battery, and DRL/REF
• Use the built-in algorithms: band powers, headband status indicator, data quality indicator, blink event, jaw clench event, and “is user wearing headband” indicator

Supported Platform: Windows 10

Compatible with
• Muse Lab (a visualization tool)
• Muse Player (a tool for file conversion)
http://www.choosemuse.com/developer/

**Comment by xqu** [comment]
这个是windows的，会对我们实验有巨大好处，因为方便。所以，1.现在谁有windows， 胡哲鹏？ 找工作班上还有谁，笑冬负责找windows 人。2. SPARK， 钱怎么花的计划，20K，核心team membr 应该人手一个windows 电脑和 mac 电脑， 人手一个apple 手机 一个android 手机，就三个人。+ 一个导师。四个电脑+四个手机。 再加上头环，我们再买个别的家的头环，再买手环，apple watch，fitbit， EEG 和ECG对比的论文。

**Comment by xqu** [comment]
windows 发展的比较多，tools 工具比较齐全。

**Comment by VenusMeow** [comment]
<img width="627" alt="screen shot 2017-10-16 at 1 59 48 pm" src="https://user-images.githubusercontent.com/32319682/31627181-5778b460-b27a-11e7-9c25-270777e88f03.png">

**Comment by VenusMeow** [comment]
http://developer.choosemuse.com/musedirect

**Comment by xqu** [comment]
在这里把 issue #1  和  #9

**Comment by xqu** [comment]
笑冬会周六再开一次讲座，顺便找windows 10 的大一大二学生。 
同时，我们现有队友继续用mac工作。
