### ISSUE TITLE
learn Kmean  priority 03

### ISSUE THREAD

**Issue by xqu** [xqu/biofeedback#14]
https://www.coursera.org/learn/machine-learning

week1
unsupervised learning 
理解什么是kmean 就可以了。

**Comment by xqu** [comment]
https://www.mathworks.com/help/stats/kmeans.html

**Comment by VenusMeow** [comment]
% classify 

[idx,X,sumd,D] = kmeans(all,numClusters);

[C,D]=museClassifyAll(all,1,X);
