### ISSUE TITLE
set up environment

### ISSUE THREAD

**Issue by VenusMeow** [xqu/biofeedback#5]
understand the existing code

**Comment by xqu** [comment]
let try it today.

**Comment by VenusMeow** [comment]
Updated version of README:

visual audio biofeedback using EEG Sensor, JavaScript

MuseJS
This is the alpha version of a basic js library for interacting with osc data sent from muse-io.

#Requirements

**MuseIO running on port 3333 sending UDP** 
Please download the right version for your device from here and install:
http://developer.choosemuse.com/research-tools/museio

**osc-web** 
Please follow the instruction to download and install: 
https://github.com/automata/osc-web
Specifically, you can follow the “installation” part of the instruction

**jQuery**
Please download from here:
https://jquery.com/download/
It’s recommended that you download the uncompressed version

**Biofeedback app.atml**
Please download the Biofeedback.zip file 

#How to use 

- Turn on your muse headband and pair up via bluetooth with your device
- On the command line(terminal/shell), enter "muse-io --osc osc.udp://localhost:3333 --dsp" to run MuseIO on port 3333 sending UDP
- On the command line, navigate to the location of osc-web by entering “cd osc-web” and then enter "node bridge.js" to run osc-web
- Open app.html from Biofeedback.zip
- Now you should be able to track your brainwave on the web page. The Muse.io window will allow you to view the percent of background noise, adjust your headband if the noise is too big. When all four coordinates of background noise are below 1%, you should see visualization of your brainwave steadily on the web page. 
- As you became more concentrated with the texts, you should be able to see change in visualization of the texts. And there will be a sound alert every minute for notification of time. 
- Please note that these are in development and may change in future iterations. Suggestions and opinions are highly welcomed. 

#Example

The example provided shows a real-time line graph of all 5 brainwaves as well as a blink event. Videos below show similar examples, but not the exact one in this repo.
https://www.youtube.com/watch?v=cYULvalaUdI
https://www.youtube.com/watch?v=EK4kR-YLFgk

**Comment by werdnaH** [comment]
Test

**Comment by werdnaH** [comment]
After I type the command " muse-io --osc osc.udp://localhost:3333 --dsp" in the powershell, it keeps loading without any results. What should I do?

**Comment by VenusMeow** [comment]
@werdnaH did you make sure that everything from requirement section is installed properly? Did you successfully connect the band with your device via bluetooth?

**Comment by xqu** [comment]
看tim 加了comment的最新版本的程序，找到声音的notification， 理解现有功能，然后尝试修改。尝试信号不好的提醒

**Comment by xqu** [comment]
Headband Status Indicator / Horseshoe

**Comment by werdnaH** [comment]
Muse lab 安装后运行显示 can't find the name of Intel ICD OpenGL driver
在网上查了解决方案，但是下载了新驱动后，驱动本身无法被安装。
用集显和独显都试过了，但是还是不行。（重启过n次）

运行 muse-lab.jar 可以解决

**Comment by xqu** [comment]
merge to clear guide
